#! /usr/bin/env ruby

require "yaml"

@address_procs = {}
@dns_procs = {}

def address(slug, &block)
	@address_procs[slug] = block
end

def dns(slug, &block)
	@dns_procs[slug] = block
end

Dir.glob(File.join(__dir__, "address_*.rb")) { |filename|
	require filename
}

Dir.glob(File.join(__dir__, "dns_*.rb")) { |filename|
	require filename
}

configs = YAML.load_file("/etc/saicoro.conf")

Process.daemon

loop {
	configs["configs"].each { |config|
		address = @address_procs[config["address"]["type"].to_sym].(config["address"]["params"])

		if address != config["prev_address"]
			@dns_procs[config["dns"]["type"].to_sym].(address, config["dns"]["params"])

			config["prev_address"] = address
		end
	}

	sleep(configs["period"])
}
